# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'Sample Swift' do
  pod 'Alamofire'
  pod 'JWT'
  pod 'TrueTime'
  # Use the following line to use App Center Analytics and Crashes.x
  pod 'Connectivity'
end